schema_version = "1.0.0"

id = "bombsquad_tools"
version = "3.0.9"
name = "BombSquad Tools"
tagline = "Tools for creating BombSquad game assets"
maintainer = "aryan02420 <aryan02420@gmail.com>"
type = "add-on"
website = "https://github.com/bombsquad02420/blender-addon"
tags = ["Import-Export", "Scene"]
blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
copyright = [
	"2016-2023 Mrmaxmeier",
	"2020-2025 aryan02420",
]

[permissions]
files = "Import/export .bob, .cob, and .json files"
